//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUSTOMERID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string ADDRESS { get; set; }
        public string STREET { get; set; }
        public string POSTCODE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<int> DOCTORID { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
